apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/isaiahwong/cluster/client/oauth
    sync:
      '**/*.js': . #Ignores js changes
deploy:
  kubectl:
    manifests:
    - k8s/oauth.yaml
