
---
##################################################
## Service
##################################################

apiVersion: v1
kind: Service
metadata:
  name: showcase-service
  labels:
    resourceType: client-service
  annotations:
    config: '{
      "expose": true,
      "path": "/",
      "apiVersion": "v1",
      "authentication": {
        "required": "false"
      }
    }'
spec:
  ports:
  - name: http
    port: 3000
    targetPort: showcase-port
  selector: 
    app: showcase
  type: ClusterIP
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: showcase
  template: 
    metadata: 
      labels: 
        app: showcase
    spec:
      containers:
      - name: showcase
        image: registry.gitlab.com/isaiahwong/kinddd/showcase
        imagePullPolicy: Always
        ports:
        - name: showcase-port
          containerPort: 5000
          
        envFrom:
        - configMapRef:
            name: showcase-env-configmap
        # - secretRef:
        #     name: showcase-env-secrets

        resources:
          requests:
            cpu: 80m
            memory: 60Mi
          limits:
            cpu: 85m
            memory: 128Mi

      imagePullSecrets:
      - name: gitlab-auth
